### ISSUE TITLE
Provide a straightforward mechanism for spinner toggling on AJAX calls

### ISSUE THREAD

**Issue by mjy** [mx3/mx#15]
Think we might have this worked out- would be nice to document how to do this for any AJAX call, including using link_to :remote => true.

**Comment by caryfitzhugh** [comment]
If you do:

```
    $.basicModal('loading');
```

That does the spinner

```
      $.basicModal('hide'); 
```

hides it.

If you want to hook into remote=>true I am pretty sure I can do that easily... since I remember reading somewhere that Rails 3 fires events on those sorts of page actions... should be easy to hook into them..  I guess put another issue in if you want me to do that.

**Comment by caryfitzhugh** [comment]
Actually, was intrigued.. and it was easier than I thought.  So - it's done. ;)
