### ISSUE TITLE
Fix the javascript add/remove authors to Refs

### ISSUE THREAD

**Issue by mjy** [mx3/mx#22]
Ref->new for example.  See production for existing functionality.

**Comment by caryfitzhugh** [comment]
working.

**Comment by caryfitzhugh** [comment]
Question for you -- I'm about done, but two things are still pending.
JS update when you rearrange, and then JS destroy callbacks when you want to destroy the author.

When we have these sorts of forms at Ziplist - we don't do AJAX updates since #1 it's simple to just skip it - but #2 - because the rest of the form is updated when you push 'save' - so users can be confused that some things get updated when I just drag it around it, and some get updated only when I push save.

It's easier to do things like rearrange in the DOM - and then just update when they push save.
You can edit it in the DOM as well (just remove elelemnts from the DOM when someone clicks 'delete' -- and when you click save, you can find out what hsould be been deleted on the server side) 

Dunno  - let me know what you want. I don't mind putting in the JS. :)
Thanks
Cary

**Comment by mjy** [comment]
Go ahead and do the JS destroy/update.  I do like logic of your
approach- but I think for the user (in mx) we'll save everytime there
is a draggable list- you'll see the same functionality for OTU groups
and Character groups as well (in those cases we don't also update the
record, it's just order).  So for consistency in the app (if it's not
too much work) let's do the JS update here.

Thanks!

On Sun, Oct 2, 2011 at 12:04 AM, caryfitzhugh
reply@reply.github.com
wrote:

**Comment by caryfitzhugh** [comment]
Update done.
Should be able to add destroy / and  then resort authors.
I never understand how form helpers work, and they always seem to break in odd ways for me - so I skipped them on the _author partial - and just did raw HTML...  So much clearer to me when I'm trying to debug things and work them out.

I'm really liking adding the data-fields to elements, then putting generic JS libraries in there.
So mx-sortable, mx-insert-element, are using this model.

I added some comments at the top of each of those libraries.

**Comment by mjy** [comment]
Cool. I'm working on the test failures right now. If you've got the
sortable figured out the other drag/drop task might be the next
logical one to tackle- might be simple.  Not sure if we nee to revisit
the acts_as_list code.

On Sun, Oct 2, 2011 at 3:42 PM, caryfitzhugh
reply@reply.github.com
wrote:

**Comment by caryfitzhugh** [comment]
Sure. I can knock those out.  Give m a task and a bit of direction and I can
get it fixed.  Thanks.
On Oct 2, 2011 3:45 PM, "Matt" <
reply@reply.github.com>
wrote:

**Comment by mjy** [comment]
#19

On Sun, Oct 2, 2011 at 7:52 PM, caryfitzhugh
reply@reply.github.com
wrote:
